name: CI

on: [push]

jobs:
  test-defaults:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/setup-elixir-project
  test-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/setup-elixir-project
        with:
          elixir-version: "1.16.1"
          otp-version: "26.2.2"
